import Head from "next/head";
import Link from "next/link";
import React from "react";
import Header from "~/pages/(components)/Header";
import { ReactNode } from "react";
import SideBar from "./Sidebar";

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <SideBar />
        <div className="flex flex-col flex-grow ml-64">
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-center bg-themecolor1">
            {children}
          </main>
        </div>
      </div>
    </>
  );
}

export default Layout;